----------
-- USER --
----------
DROP USER BF CASCADE;
CREATE USER BF IDENTIFIED BY BF;
GRANT CONNECT TO BF;
GRANT RESOURCE TO BF;
------------
-- GRANTS --
------------
GRANT DBA TO OJ05;
---------------
-- SEQUENCES --
---------------
CREATE SEQUENCE  "BF"."SQ_APRESENTACAO"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 ;
------------
-- TABLES --
------------
CREATE TABLE "BF"."APRESENTACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITULO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"APRESENTADOR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VERDE" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"AMARELO" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"VERMELHO" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "APRESENTACAO_PK" PRIMARY KEY ("ID"));
-------------
-- INSERTS --
-------------
INSERT INTO BF.APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO,
STATUS ) VALUES ( 
1, 'Titulo 1', 'Apres 1', 0, 0, 0, 'A'); 
INSERT INTO BF.APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO,
STATUS ) VALUES ( 
2, 'Titulo 2', 'Apres 1', 0, 0, 0, 'A'); 
INSERT INTO BF.APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO,
STATUS ) VALUES ( 
3, 'Titulo 3', 'Apres 1', 0, 0, 0, 'A'); 
COMMIT;
