DROP SEQUENCE  "BF"."SQ_APRESENTACAO";

DROP TABLE "BF"."APRESENTACAO";

CREATE SEQUENCE  "BF"."SQ_APRESENTACAO"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 ;

CREATE TABLE "BF"."APRESENTACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITULO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"APRESENTADOR" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VERDE" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"AMARELO" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"VERMELHO" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "APRESENTACAO_PK" PRIMARY KEY ("ID"));

