INSERT INTO APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO, STATUS ) VALUES ( 1, 'Titulo 1', 'Apres 1', 0, 0, 0, 'ABERTA'); 
INSERT INTO APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO, STATUS ) VALUES ( 2, 'Titulo 2', 'Apres 1', 0, 0, 0, 'ABERTA'); 
INSERT INTO APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO, STATUS ) VALUES ( 3, 'Titulo 3', 'Apres 1', 0, 0, 0, 'ABERTA'); 
INSERT INTO APRESENTACAO ( ID, TITULO, APRESENTADOR, VERDE, AMARELO, VERMELHO, STATUS ) VALUES ( 4, 'Titulo 4', 'Apres 1', 15, 2, 3, 'ENCERRADA'); 